version: "3.8"
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: codelicious
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "33306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
